// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOMpnsHp2V62ZCOf_GXiCmhrlGvRTLuxc',
    appId: '1:794372578685:web:b69a21bd72c28e88458014',
    messagingSenderId: '794372578685',
    projectId: 'dbtodo-8d0ee',
    authDomain: 'dbtodo-8d0ee.firebaseapp.com',
    storageBucket: 'dbtodo-8d0ee.appspot.com',
    measurementId: 'G-6ZJJ2G3MW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZMNdUnvPrykLOu0lbb3C9FkCzCMakbn8',
    appId: '1:794372578685:android:a31c985b477eb9fa458014',
    messagingSenderId: '794372578685',
    projectId: 'dbtodo-8d0ee',
    storageBucket: 'dbtodo-8d0ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo8iEEEF_VC3rBIN6libJSnG3XZjclZeQ',
    appId: '1:794372578685:ios:28c76f07a544e4f3458014',
    messagingSenderId: '794372578685',
    projectId: 'dbtodo-8d0ee',
    storageBucket: 'dbtodo-8d0ee.appspot.com',
    iosBundleId: 'pk.intellilogics.week6Firebase',
  );
}
